nameReference:
  - kind: Gateway
    version: v1
    group: gateway.networking.k8s.io
    fieldSpecs:
      - kind: HTTPRoute
        version: v1
        group: gateway.networking.k8s.io
        path: spec/parentRefs/name
