apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app.kubernetes.io/name: frontend-ingress
spec:
  # Specify the app routing ingress class
  # The ingress class is got from command kubectl get ingressclass which should return two ingress classes
  # This references the ingress class that is created in defaults ingress class yaml file
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: front.weatherly
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
