apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-httproute
spec:
  parentRefs:
    - name: backend-gateway
      # maps to listener named http in backend-gateway (useful for gateways with multiple listeners)
      sectionName: http
  hostnames:
    - api.weatherly
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-service
          port: 8080