apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: backend-gateway
spec:
  gatewayClassName: nginx-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      host: api.weatherly
