apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  namespace: default
  name: backend-kustomization

resources:
  - backend_deployment.yaml
  - auto-scaling/backend_hpa.yaml
  - auto-scaling/backend_pod-disruption-budget.yaml
  - gateway-api/backend_gateway-api.yaml
  - gateway-api/backend_httproute.yaml
  - gateway-api/backend_reference-grant.yaml
  - gateway-api/backend_service.yaml