apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: database-kustomization

resources:
  - redis/redis_stateful-set.yaml
  - redis/services/redis_write-service.yaml
  - redis/services/redis_read-service.yaml
  - redis/services/redis_headless-service.yaml