apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: default
  name: frontend-kustomization

resources:
  - frontend_deployment.yaml
  - auto-scaling/frontend_hpa.yaml
  - auto-scaling/frontend_pod-disruption-budget.yaml
  - gateway-api/frontend_gateway-api.yaml
  - gateway-api/frontend_httproute.yaml
  - gateway-api/frontend_service.yaml
  - config/frontend_config-map.yaml

configurations:
  - kustomizeconfig.yaml