apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-httproute
  namespace: istio-gateway
  labels:
    app: frontend
    version: v1
spec:
  parentRefs:
    - name: backend-gateway
      # maps to listener named http in backend-gateway (useful for gateways with multiple listeners)
      sectionName: http
  hostnames:
    #maps to one or many of the host names that are defined on the gateway level
    - api.weatherly.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-service
          port: 8080
          namespace: backend