# This is a cluster IP service that points to the specific redis primary pod (redis-0)
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: backend
spec:
  ports:
  - port: 6379
  selector:
    # writes are directed to redis-0 pod
    statefulset.kubernetes.io/pod-name: dev-redis-0
  type: ClusterIP
