apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: frontend
  labels:
    app: frontend-configmap
data:
  appSettings.yaml: |
    # yaml file
    backend_url: http://api.weatherly.local:8080
