services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  weather-forecast-api:
    build:
      context: ./weather-forecast-api
      dockerfile: DockerFile
    container_name: weather-forecast-api
    depends_on:
      - redis
    environment:
      WeatherForecast__Redis__ReadDbConnection: "redis:6379,abortConnect=false,connectRetry=10"
      WeatherForecast__Redis__WriteDbConnection: "redis:6379,abortConnect=false,connectRetry=10"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:80"
    restart: always
    command: ["/app/wait-for.sh", "redis", "6379", "dotnet", "WeatherForecast.Api.dll"]
  weather-forecast-frontend:
    build:
      context: ./weather-forecast-frontend
      dockerfile: DockerFile
    depends_on:
      - weather-forecast-api
    environment:
      # Point frontend to backend container
      BACKEND_URL: "http://weather-forecast-api:5000"
    container_name: weather-forecast-frontend
    ports:
      - "8080:80"
    restart: always