apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  appSettings.json: |
    # json fieldPath:
    "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
      }
    },
    "AllowedHosts": "*"
    "WeatherForecast":{
      "Redis": {
          "WriteDbConnection": "redis-primary.default.svc.cluster.local:6379"
          "ReadDbConnection": "redis-secondary.default.svc.cluster.local:6379"
        }
    }