name: CI - Build & Push Weather Forecast Frontend

on:
    push:
        branches: [ "main" ]
        paths:
          - src/weather-forecast-frontend/**
    pull_request:
        paths:
          - src/weather-forecast-frontend/**
    workflow_dispatch:

jobs:
    Frontend-BuildAndPush:
        uses: ./.github/workflows/ci-template.yml
        with:
            service_name: weather-forecast-frontend
            service_path: src/weather-forecast-frontend
            gitversion_config_path: src/weather-forecast-frontend/GitVersion.yml
        secrets:
            ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
            ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
            ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
